### ISSUE TITLE
Добавяне на фамилни имена

### ISSUE THREAD

**Issue by NedkoHristov** [dimddev/bulgarian-names#1]
Първо - благодаря за листинга.

Второ - мисля, че ще е добре към първите имена да добавиш и фамилни такива.

**Comment by dimddev** [comment]
Привет, ако имаш списък, може да го добавим, аз лично не разполагам с такъв, но също на база тези имена може да се съставят или проверяват бащини и фамилни, само трябва да се види какъв е патерна за окончанията, като "ов", "ев" и тн,
